# Maven   xjhl
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

# trigger:
# - master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: CopyFiles@2
  inputs:
    Contents: '**/*.war'
    TargetFolder: '$(build.artifactstagingdirectory)'


- task: AzureCLI@2
  inputs:
    azureSubscription: 'dataupload'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "$(Build.ArtifactStagingDirectory) is the path"
      cd $(Build.ArtifactStagingDirectory)
      pwd;ls
      az storage blob upload --account-name automationstt23484 --account-key $(Acct_key) \ 
      --container-name remotestatebackend --file /home/vsts/work/1/a/webapp.war --name webapp.war --overwrite
